# Numpy를 이용한 배열 데이터의 생성

In [4]:
import numpy as np

lst_data=[1,2,3,4]
str_lst=['abc','def','123']

arr1=np.array([10,20,30,40]) 
arr2=np.array(lst_data)
arr3=np.array(str_lst)
arr4=arr1+arr2

print(arr1)
print(arr2)
print(arr3)
print(arr4)
print(arr1+arr2)
# print(arr1+arr3)   # arr1 : 숫자,  arr3 : 문자열   

[10 20 30 40]
[1 2 3 4]
['abc' 'def' '123']
[11 22 33 44]
[11 22 33 44]


# Numpy로 이중 배열 데이터 생성

In [ ]:
import numpy as np

lst_data=[[10,20,30],[40,50,60]]
arr1=np.array(lst_data)
print(arr1)

# 