## Numpy를 이용한 배열 데이터의 생성

In [1]:
import numpy as np

lst_data=[1,2,3,4]
str_lst=['abc','def','123']

arr1=np.array([10,20,30,40]) 
arr2=np.array(lst_data)
arr3=np.array(str_lst)
arr4=arr1+arr2

print(arr1)
print(arr2)
print(arr3)
print(arr4)
print(arr1+arr2)
# print(arr1+arr3)   # arr1 : 숫자,  arr3 : 문자열   

[10 20 30 40]
[1 2 3 4]
['abc' 'def' '123']
[11 22 33 44]
[11 22 33 44]


## Numpy로 이중 배열 데이터 생성

In [2]:
import numpy as np

lst_data=[[10,20,30],[40,50,60]]
arr1=np.array(lst_data)
print(arr1)

[[10 20 30]
 [40 50 60]]


## arange로 배열 생성 : (시작값, 종료값, 단계값)
### 시작값 : 0, 단계값 : 1  이 기본값 이며 생략 가능, 종료값은 미만값으로 포함되지 않는다

In [3]:
import numpy as np

arr1=np.arange(0,20,3)  # 시작값 : 0  종료값 : 20   단계값 : 3
arr2=np.arange(0,10)    #  시작값 : 0   종료값 : 10  (단계값 : 1)
arr3=np.arange(10)      #  (시작값 : 0)  종료값 : 10  (단계값 : 1)

print(arr1)
print(arr2)
print(arr3)

[ 0  3  6  9 12 15 18]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


## linspace(시작값, 종료값, 배열원소의 개수)
### 시작값 ~ 종료값 사이에 배열원소의 갯수 만큼으리 요소를 가는 배열을 생성

In [4]:
import numpy as np
arr1=np.linspace(0,100,5)
arr1


array([  0.,  25.,  50.,  75., 100.])

### array.shape  :  array 형태를 반환

In [5]:
import numpy as np
arr1=np.array([0,1,2,3,4,5])
arr2=np.array([0,1,2,3])
arr3=np.array([[1,2,3],[4,5,6],[7,8,9]])

print(arr1.shape)
print(arr2.shape)
print(arr3.shape)

(6,)
(4,)
(3, 3)
